# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x projects/1.7/gradlew projects/1.12/gradlew
    - name: Build with Gradle
      run: sh ./clean_build_all.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: projects/*/build/libs
